### ISSUE TITLE
Panic instead of returning Result

### ISSUE THREAD

**Issue by glyn** [razvanperial/cryptographic_primitives#1]
Just taking an initial look at this code and I noticed that `feistel_network_encrypt` is documented as returning one of three errors, but in the case of HMAC creation failures, the code actually panics instead of returning a Result.

I'm not sure what was intended here. Should the docs simply say that the third case is a panic? Or should the HMAC creation failures return an error Result?

**Comment by razvanperial** [comment]
That's a good point, I will fix this and make it return an Error instead of panicking in the next commit. Thanks for the feedback!

**Comment by glyn** [comment]
Thanks. Please could you also document precisely when the HMAC-related
errors can occur. I can't tell whether these are avoidable, e.g. by choice
of a suitable key.

**Comment by razvanperial** [comment]
I just published version 0.2.0 of the crate, and now the function throws an error instead of panicking.

Regarding your comment regarding when precisely this error can occur, I initially thought that an incorrect key length could cause this, but after further testing this was not the case. Essentially, for that error to occur, then [this function](https://docs.rs/crypto-common/latest/src/crypto_common/lib.rs.html#129-135) should fail. The way the `kdf` function is implemented in this crate, this is very unlikely to happen. If for some reason the internal structure of the key data is corrupted in a way that causes the HMAC library to misbehave, then maybe the funcion could throw this error, but I couldn't manage to make this happen. I did leave the error handling in there on the principle of "Better safe than sorry":)

I hope this covers this topic. If yes, let me know and I will close this issue.

**Comment by glyn** [comment]
Thanks @razvanperial!

## Error handling instead of panic

Although the new code is correct, it could be made shorter by using [error propagation](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator). For example:
~~~
        let xored_chunk = match xor_bytes(&decrypted_chunk, &prev_block) {
            Ok(c) => c,
            Err(e) => return Err(e),
        };
~~~
in a function which returns `Result` with a suitable error type, could be replaced by:
~~~
        let xored_chunk = xor_bytes(&decrypted_chunk, &prev_block)?;
~~~ 

## Unknown precondition for error

Since I can't tell when errors will occur, I'm afraid I won't be able to use this code for [my usecase](https://underlap.org/open-development-experiment-cryptographic-primitives). Your usecase may be different. But thanks very much for your response above.

**Comment by razvanperial** [comment]
Thank you for the feedback, it's much appreciated!

Regarding your usecase, if this theoretical error is the only blocker, then I'm sure you will be safe as long as you pick a 128bit key. With the latest commit, I tried to cover as many edge cases as I could think about with my tests, and there was no error thrown as long as the 2 preconditions (non-empty input array & the no. of rounds bigger than 0) were met. 

In any case, I wish you good luck with your project!

**Comment by glyn** [comment]
Thank you!
